- 2025-05-27：增加重试拉取逻辑

diff --git a/.github/workflows/switchScript.yaml b/.github/workflows/switchScript.yaml
--- a/.github/workflows/switchScript.yaml
+++ b/.github/workflows/switchScript.yaml
@@ -36,7 +36,31 @@ jobs:
         echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
         echo "tag_name=$(date +%Y%m%d)" >> $GITHUB_ENV
         chmod +x $SCRIPT_SH
-        ./$SCRIPT_SH
+
+        # Add retry logic here
+        max_attempts=3
+        attempt_num=1
+        while [ $attempt_num -le $max_attempts ]; do
+          echo "Attempt $attempt_num to run the script..."
+          if ./$SCRIPT_SH; then
+            echo "Script executed successfully on attempt $attempt_num."
+            break
+          else
+            echo "Script failed on attempt $attempt_num."
+            if [ $attempt_num -lt $max_attempts ]; then
+              echo "Retrying in 10 seconds..." # Optional: add a delay
+              sleep 10
+            fi
+            attempt_num=$((attempt_num+1))
+          fi
+        done
+
+        # Check if the script ultimately failed after retries
+        if [ $attempt_num -gt $max_attempts ]; then
+          echo "Script failed after $max_attempts attempts."
+          exit 1 # Exit with a non-zero status to indicate failure
+        fi
+
         zip -rq SwitchSD.zip SwitchSD
 
     - name: Read description.txt
